# Generated by Django 5.0 on 2024-01-01 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='brand_images')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cars')),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('hire_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=uuid.uuid4, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('brand', models.ManyToManyField(related_name='brands', to='a_main.category')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
