# Generated by Django 5.0 on 2024-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
