# Generated by Django 5.0 on 2024-01-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='hire_rate',
            new_name='hire_rate_day',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('electric', 'electric')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='hire_rate_hour',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='lease_rate',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='luggage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
