# Generated by Django 5.0 on 2024-01-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_main', '0004_alter_bookmark_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-date_bookmarked']},
        ),
        migrations.AlterField(
            model_name='carrental',
            name='drop_off_date',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='drop_off_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='pick_up_date',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='pick_up_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='pick_up_time',
            field=models.TimeField(max_length=200, null=True),
        ),
    ]
