# Generated by Django 5.0 on 2024-01-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_main', '0005_alter_bookmark_options_alter_carrental_drop_off_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='drop_off_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='drop_off_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='pick_up_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='pick_up_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='pick_up_time',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
    ]
